name:  Deploy Static Site to Netlify

# Триггер: когда запускать этот workflow
on:
  push:
    branches:
      - main 

jobs:
  # Название первого задания: сборка и тестирование
  build_and_test:
    runs-on: ubuntu-latest # Используем последнюю виртуальную машину Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Скачиваем код из репозитория

      - name: Run tests
        run: |
          chmod +x test_script.sh # Делаем скрипт исполняемым
          ./test_script.sh         # Запускаем наш скрипт тестирования
          echo "Tests completed."
  deploy:
    needs: build_and_test # Запускать только после успешного завершения build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Netlify
        uses: netlify/actions/cli
        with:
          args: deploy --prod --dir=.
        env:
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
    if: needs.build_and_test.result == 'success'
