name: Deploy Static Site to GitHub Pages

# Триггер: когда запускать этот workflow
on:
  push:
    branches:
      - main 

jobs:
  # Название первого задания: сборка и тестирование
  build_and_test:
    runs-on: ubuntu-latest # Используем последнюю виртуальную машину Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Скачиваем код из репозитория

      - name: Run tests
        run: |
          chmod +x test_script.sh # Делаем скрипт исполняемым
          ./test_script.sh         # Запускаем наш скрипт тестирования

  deploy:
    needs: build_and_test # Запускать только после успешного завершения build_and_test
    runs-on: ubuntu-latest
    permissions:
      contents: write # Требуются права на запись в репозиторий для GitHub Pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Получаем всю историю коммитов для развертывания

      # GitHub Actions предоставляет готовый action для развертывания на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4 # Используем готовый action для развертывания
        with:
          artifact_path: '.' # Путь к файлам, которые нужно развернуть

    # Условия запуска
    only:
      branches:
        - main # Развертывать только из ветки main
    # Указываем, что этот job запускается только если предыдущий job успешен
    if: needs.build_and_test.result == 'success'
